In [1]:
import pandas as pd 

# Loading data and getting overall info
df = pd.read_csv('/Users/janek/Documents/Data Analysis Learning/EDA Project/amazon-laptops-EDA/data_cleaning/laptops_clean.csv')
df.head() 
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 141 entries, 0 to 140
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     141 non-null    int64
 1   product_title          141 non-null    object
 2   rating                 128 non-null    float64
 3   total_rating           127 non-null    object
 4   price                  141 non-null    int64
 5   final_price            135 non-null    float64
 6   ram_gb                 139 non-null    float64
 7   storage_gb             134 non-null    float64
 8   bought_in_last_month   57 non-null     float64
 9   brand                  141 non-null    object
 10  screen_size_in_inches  140 non-null    float64
 11  cpu_model              138 non-null    object
 12  special_features       133 non-null    object
 13  graphics_card          140 non-null    object
 14  os                     140 non-null    object
dtypes: float64(6), int64(2), object(7)
memory usage: 16.7+ KB

,id,rating,price,final_price,ram_gb,storage_gb,bought_in_last_month,screen_size_in_inches
count,141.000000,128.000000,141.000000,135.000000,139.000000,134.000000,57.000000,140.000000
mean,102.049645,3.882812,86918.475177,89202.570370,17.366906,337.104478,149.122807,126.542857
std,63.165918,0.637677,86462.087334,97941.726551,11.597191,242.631974,123.379217,122.743071
min,0.000000,1.000000,10990.000000,12090.000000,4.000000,1.000000,50.000000,14.000000
25%,46.000000,3.700000,37600.000000,38145.000000,16.000000,1.250000,50.000000,16.000000
50%,109.000000,4.000000,57990.000000,56011.000000,16.000000,512.000000,100.000000,141.000000
75%,159.000000,4.200000,99990.000000,94990.000000,16.000000,512.000000,200.000000,156.000000
max,206.000000,5.000000,499990.000000,617990.000000,96.000000,1000.000000,500.000000,406.000000

In [2]:
df['bought_in_last_month'] = df['bought_in_last_month'].fillna(0)

In [3]:
mode_rating = df['rating'].mode()[0]
df['rating'] = df['rating'].fillna(mode_rating) 

mode_ram = df['ram_gb'].mode()[0]
df['ram_gb'] = df['ram_gb'].fillna(mode_ram)

mode_storage = df['storage_gb'].mode()[0]
df['storage_gb'] = df['storage_gb'].fillna(mode_storage)

In [4]:
df.describe()

,id,rating,price,final_price,ram_gb,storage_gb,bought_in_last_month,screen_size_in_inches
count,141.000000,141.000000,141.000000,135.000000,141.000000,141.000000,141.000000,140.000000
mean,102.049645,3.893617,86918.475177,89202.570370,17.347518,345.787234,60.283688,126.542857
std,63.165918,0.608301,86462.087334,97941.726551,11.515199,239.541759,107.157716,122.743071
min,0.000000,1.000000,10990.000000,12090.000000,4.000000,1.000000,0.000000,14.000000
25%,46.000000,3.700000,37600.000000,38145.000000,16.000000,2.000000,0.000000,16.000000
50%,109.000000,4.000000,57990.000000,56011.000000,16.000000,512.000000,0.000000,141.000000
75%,159.000000,4.100000,99990.000000,94990.000000,16.000000,512.000000,100.000000,156.000000
max,206.000000,5.000000,499990.000000,617990.000000,96.000000,1000.000000,500.000000,406.000000

In [5]:
df['final_price'] = df['final_price'].fillna(df['price']) #probably there was no sale

In [6]:
df.describe()

,id,rating,price,final_price,ram_gb,storage_gb,bought_in_last_month,screen_size_in_inches
count,141.000000,141.000000,141.000000,141.000000,141.000000,141.000000,141.000000,140.000000
mean,102.049645,3.893617,86918.475177,90059.595745,17.347518,345.787234,60.283688,126.542857
std,63.165918,0.608301,86462.087334,97293.370122,11.515199,239.541759,107.157716,122.743071
min,0.000000,1.000000,10990.000000,12090.000000,4.000000,1.000000,0.000000,14.000000
25%,46.000000,3.700000,37600.000000,36990.000000,16.000000,2.000000,0.000000,16.000000
50%,109.000000,4.000000,57990.000000,56011.000000,16.000000,512.000000,0.000000,141.000000
75%,159.000000,4.100000,99990.000000,99990.000000,16.000000,512.000000,100.000000,156.000000
max,206.000000,5.000000,499990.000000,617990.000000,96.000000,1000.000000,500.000000,406.000000

In [8]:
df['screen_size_in_inches'] = df.groupby('brand')['screen_size_in_inches'].transform( #grouping - screen size is not continuous
    lambda x: x.fillna(x.mode()[0] if not x.mode().empty else x)
)

In [9]:
df.describe()

,id,rating,price,final_price,ram_gb,storage_gb,bought_in_last_month,screen_size_in_inches
count,141.000000,141.000000,141.000000,141.000000,141.000000,141.000000,141.000000,141.000000
mean,102.049645,3.893617,86918.475177,90059.595745,17.347518,345.787234,60.283688,126.751773
std,63.165918,0.608301,86462.087334,97293.370122,11.515199,239.541759,107.157716,122.329074
min,0.000000,1.000000,10990.000000,12090.000000,4.000000,1.000000,0.000000,14.000000
25%,46.000000,3.700000,37600.000000,36990.000000,16.000000,2.000000,0.000000,16.000000
50%,109.000000,4.000000,57990.000000,56011.000000,16.000000,512.000000,0.000000,141.000000
75%,159.000000,4.100000,99990.000000,99990.000000,16.000000,512.000000,100.000000,156.000000
max,206.000000,5.000000,499990.000000,617990.000000,96.000000,1000.000000,500.000000,406.000000

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 141 entries, 0 to 140
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     141 non-null    int64
 1   product_title          141 non-null    object
 2   rating                 141 non-null    float64
 3   total_rating           127 non-null    object
 4   price                  141 non-null    int64
 5   final_price            141 non-null    float64
 6   ram_gb                 141 non-null    float64
 7   storage_gb             141 non-null    float64
 8   bought_in_last_month   141 non-null    float64
 9   brand                  141 non-null    object
 10  screen_size_in_inches  141 non-null    float64
 11  cpu_model              138 non-null    object
 12  special_features       133 non-null    object
 13  graphics_card          140 non-null    object
 14  os                     140 non-null    object
dtypes: float64(6), int64(2), object(7)
memory usage: 16.7+ KB

In [11]:
df['special_features'] = df['special_features'].fillna('')

In [12]:
df['total_rating'] = df['total_rating'].str.replace(r'[^\d]', '', regex=True)
df['total_rating'] = pd.to_numeric(df['total_rating']).fillna(0)

In [13]:
df.describe()

,id,rating,total_rating,price,final_price,ram_gb,storage_gb,bought_in_last_month,screen_size_in_inches
count,141.000000,141.000000,141.000000,141.000000,141.000000,141.000000,141.000000,141.000000,141.000000
mean,102.049645,3.893617,233.815603,86918.475177,90059.595745,17.347518,345.787234,60.283688,126.751773
std,63.165918,0.608301,436.053709,86462.087334,97293.370122,11.515199,239.541759,107.157716,122.329074
min,0.000000,1.000000,0.000000,10990.000000,12090.000000,4.000000,1.000000,0.000000,14.000000
25%,46.000000,3.700000,5.000000,37600.000000,36990.000000,16.000000,2.000000,0.000000,16.000000
50%,109.000000,4.000000,45.000000,57990.000000,56011.000000,16.000000,512.000000,0.000000,141.000000
75%,159.000000,4.100000,277.000000,99990.000000,99990.000000,16.000000,512.000000,100.000000,156.000000
max,206.000000,5.000000,2488.000000,499990.000000,617990.000000,96.000000,1000.000000,500.000000,406.000000

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 141 entries, 0 to 140
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     141 non-null    int64
 1   product_title          141 non-null    object
 2   rating                 141 non-null    float64
 3   total_rating           141 non-null    float64
 4   price                  141 non-null    int64
 5   final_price            141 non-null    float64
 6   ram_gb                 141 non-null    float64
 7   storage_gb             141 non-null    float64
 8   bought_in_last_month   141 non-null    float64
 9   brand                  141 non-null    object
 10  screen_size_in_inches  141 non-null    float64
 11  cpu_model              138 non-null    object
 12  special_features       141 non-null    object
 13  graphics_card          140 non-null    object
 14  os                     140 non-null    object
dtypes: float64(7), int64(2), object(6)
memory usage: 16.7+ KB